name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_IMAGE}}:${{secrets.DOCKER_IMAGE_VERSION}} .

      - name: Verify Docker imagedockerapp
        run: docker images | grep ${{secrets.DOCKER_IMAGE}}:${{secrets.DOCKER_IMAGE_VERSION}}

      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{secrets.DOCKER_IMAGE_VERSION}}
